# Generated by Django 5.0.7 on 2024-08-02 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_history',
            name='bookdate',
            field=models.DateField(default=datetime.datetime(2024, 8, 2, 6, 53, 20, 254423, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concession_history',
            name='discount_amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concession_history',
            name='discount_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
