# Generated by Django 5.0.7 on 2024-08-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_concession_history_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concession_history',
            name='discount_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='concession_history',
            name='discount_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
