# Generated by Django 5.0.7 on 2024-08-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_concession_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concession_discount',
            name='discount_amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concession_discount',
            name='discount_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
