# Generated by Django 5.0.7 on 2024-08-06 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_concession_discount_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Duedate',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 8, 6, 6, 49, 24, 390982, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
