# Generated by Django 5.0.7 on 2024-08-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_user_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Duedate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
