# Generated by Django 5.0.7 on 2024-08-08 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_user_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.user'),
        ),
    ]
