# Generated by Django 5.0.6 on 2024-08-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_booking_history_secretcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
